//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Game
{
	public virtual PlayingCourt PlayingCourt
	{
		get;
		set;
	}

	public virtual void ChangeTurn()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CheckWin()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool isTie()
	{
		throw new System.NotImplementedException();
	}

	public virtual void NewGame()
	{
		throw new System.NotImplementedException();
	}

	public virtual void PlayAgain()
	{
		throw new System.NotImplementedException();
	}

	public virtual void WinnerIs()
	{
		throw new System.NotImplementedException();
	}

}

