//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Player
{
	public virtual string Name
	{
		get;
		set;
	}

	public virtual int Score
	{
		get;
		set;
	}

	public virtual char xORo
	{
		get;
		set;
	}

	public virtual bool Turn
	{
		get;
		set;
	}

	public virtual bool Win
	{
		get;
		set;
	}

	public virtual int ID
	{
		get;
		set;
	}

	public virtual Game Game
	{
		get;
		set;
	}

	public virtual void Play()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Choose_xORo()
	{
		throw new System.NotImplementedException();
	}

}

