//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PlayingCourt
{
	public virtual char[] CourtMatrix
	{
		get;
		set;
	}

	public virtual Player Player
	{
		get;
		set;
	}

	public virtual void ClearCourt()
	{
		throw new System.NotImplementedException();
	}

	public virtual void EnableButtons(object Booleam)
	{
		throw new System.NotImplementedException();
	}

	public virtual void EditScore(object Integer, object Integer)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ShowName(object String, object String)
	{
		throw new System.NotImplementedException();
	}

}

