//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Game
{
	public PlayingCourt PlayingCourt { get; set; }

	public void ChangeTurn()
	{
	}

	public void CheckWin()
	{
	}

	public bool isTie()
	{
		throw new System.NotImplementedException();
	}

	public void NewGame()
	{
	}

	public void PlayAgain()
	{
	}

	public void WinnerIs()
	{
	}
}