//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using TicTacToe;


public class PlayingCourt
{
    public Player Player { get; set; }
    //public PlayingCourtForm CourtForm { get; set; }
	public char[] CourtMatrix { get; set; }


	public void ClearCourt()
	{
        EnableButtons(true);
	}

	public void EnableButtons(bool enable)
    {
        /*button1.Enabled = enable;
        button2.Enabled = enable;
        button3.Enabled = enable;
        button4.Enabled = enable;
        button5.Enabled = enable;
        button6.Enabled = enable;
        button7.Enabled = enable;
        button8.Enabled = enable;
        button9.Enabled = enable;*/
	}

	public void EditScore(int id)
	{
        /*if (id = 1)
            label3.Text = Player.Score++;
        else if (id = 2)
            label4.Text = Player.Score++;*/
    }

	public void ShowName(String name1, String name2)
	{
        /*label1.Text = name1;
        label2.Text = name2;*/
	}
}

